[2022-10-16 22:38:46,479] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_deps scheduled__2022-10-13T00:04:00+00:00 [queued]>
[2022-10-16 22:38:46,486] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_deps scheduled__2022-10-13T00:04:00+00:00 [queued]>
[2022-10-16 22:38:46,486] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-16 22:38:46,486] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-16 22:38:46,486] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-16 22:38:46,500] {taskinstance.py:1377} INFO - Executing <Task(DbtDepsOperator): dbt_deps> on 2022-10-13 00:04:00+00:00
[2022-10-16 22:38:46,503] {standard_task_runner.py:52} INFO - Started process 253203 to run task
[2022-10-16 22:38:46,510] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dbt', 'dbt_deps', 'scheduled__2022-10-13T00:04:00+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/dbt_airflow.py', '--cfg-path', '/tmp/tmpguk6tsrc', '--error-file', '/tmp/tmp63jn9qar']
[2022-10-16 22:38:46,510] {standard_task_runner.py:80} INFO - Job 96: Subtask dbt_deps
[2022-10-16 22:38:46,580] {task_command.py:370} INFO - Running <TaskInstance: dbt.dbt_deps scheduled__2022-10-13T00:04:00+00:00 [running]> on host ubuntu
[2022-10-16 22:38:46,668] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt
AIRFLOW_CTX_TASK_ID=dbt_deps
AIRFLOW_CTX_EXECUTION_DATE=2022-10-13T00:04:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-13T00:04:00+00:00
[2022-10-16 22:38:46,669] {dbt_hook.py:117} INFO - dbt deps
[2022-10-16 22:38:46,676] {dbt_hook.py:126} INFO - Output:
[2022-10-16 22:38:49,821] {dbt_hook.py:130} INFO - 05:38:49  Running with dbt=1.1.0
[2022-10-16 22:38:49,834] {dbt_hook.py:130} INFO - 05:38:49  Warning: No packages were found in packages.yml
[2022-10-16 22:38:51,370] {dbt_hook.py:132} INFO - Command exited with return code 0
[2022-10-16 22:38:51,382] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dbt, task_id=dbt_deps, execution_date=20221013T000400, start_date=20221017T053846, end_date=20221017T053851
[2022-10-16 22:38:51,415] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-16 22:38:51,459] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
