[2022-10-13 14:23:27,328] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt_dag_bash.dbt_run manual__2022-10-13T21:22:59.806022+00:00 [queued]>
[2022-10-13 14:23:27,333] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt_dag_bash.dbt_run manual__2022-10-13T21:22:59.806022+00:00 [queued]>
[2022-10-13 14:23:27,333] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-13 14:23:27,333] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-13 14:23:27,333] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-13 14:23:27,345] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): dbt_run> on 2022-10-13 21:22:59.806022+00:00
[2022-10-13 14:23:27,348] {standard_task_runner.py:52} INFO - Started process 250824 to run task
[2022-10-13 14:23:27,352] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag_bash', 'dbt_run', 'manual__2022-10-13T21:22:59.806022+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/dbt_bashOperator.py', '--cfg-path', '/tmp/tmp8rq1ehss', '--error-file', '/tmp/tmppemqas4g']
[2022-10-13 14:23:27,352] {standard_task_runner.py:80} INFO - Job 91: Subtask dbt_run
[2022-10-13 14:23:27,406] {task_command.py:370} INFO - Running <TaskInstance: dbt_dag_bash.dbt_run manual__2022-10-13T21:22:59.806022+00:00 [running]> on host ubuntu
[2022-10-13 14:23:27,479] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt_dag_bash
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2022-10-13T21:22:59.806022+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-13T21:22:59.806022+00:00
[2022-10-13 14:23:27,483] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-13 14:23:27,484] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /home/ubuntu/airflow/dbt_project/ && dbt run -m Core']
[2022-10-13 14:23:27,505] {subprocess.py:85} INFO - Output:
[2022-10-13 14:23:30,735] {subprocess.py:92} INFO - 21:23:30  Running with dbt=1.1.0
[2022-10-13 14:23:30,901] {subprocess.py:92} INFO - 21:23:30  Found 6 models, 5 tests, 6 snapshots, 0 analyses, 400 macros, 0 operations, 7 seed files, 2 sources, 0 exposures, 0 metrics
[2022-10-13 14:23:30,905] {subprocess.py:92} INFO - 21:23:30
[2022-10-13 14:23:34,006] {subprocess.py:92} INFO - 21:23:34  Concurrency: 2 threads (target='dev')
[2022-10-13 14:23:34,006] {subprocess.py:92} INFO - 21:23:34
[2022-10-13 14:23:34,013] {subprocess.py:92} INFO - 21:23:34  1 of 2 START incremental model DBT_HAMS71.Core_City ............................ [RUN]
[2022-10-13 14:23:34,022] {subprocess.py:92} INFO - 21:23:34  2 of 2 START incremental model DBT_HAMS71.Core_Transactions .................... [RUN]
[2022-10-13 14:23:36,556] {subprocess.py:92} INFO - 21:23:36  1 of 2 OK created incremental model DBT_HAMS71.Core_City ....................... [[32mSUCCESS 1[0m in 2.54s]
[2022-10-13 14:23:36,558] {subprocess.py:92} INFO - 21:23:36  2 of 2 OK created incremental model DBT_HAMS71.Core_Transactions ............... [[32mSUCCESS 1[0m in 2.53s]
[2022-10-13 14:23:36,561] {subprocess.py:92} INFO - 21:23:36
[2022-10-13 14:23:36,561] {subprocess.py:92} INFO - 21:23:36  Finished running 2 incremental models in 5.66s.
[2022-10-13 14:23:36,580] {subprocess.py:92} INFO - 21:23:36
[2022-10-13 14:23:36,580] {subprocess.py:92} INFO - 21:23:36  [32mCompleted successfully[0m
[2022-10-13 14:23:36,581] {subprocess.py:92} INFO - 21:23:36
[2022-10-13 14:23:36,581] {subprocess.py:92} INFO - 21:23:36  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
[2022-10-13 14:23:38,292] {subprocess.py:96} INFO - Command exited with return code 0
[2022-10-13 14:23:38,325] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dbt_dag_bash, task_id=dbt_run, execution_date=20221013T212259, start_date=20221013T212327, end_date=20221013T212338
[2022-10-13 14:23:38,367] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-13 14:23:38,392] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
