[2022-10-13 14:25:42,470] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt_dag_bash.dbt_docs manual__2022-10-13T21:22:59.806022+00:00 [queued]>
[2022-10-13 14:25:42,476] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt_dag_bash.dbt_docs manual__2022-10-13T21:22:59.806022+00:00 [queued]>
[2022-10-13 14:25:42,476] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-13 14:25:42,476] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-10-13 14:25:42,476] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-13 14:25:42,490] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): dbt_docs> on 2022-10-13 21:22:59.806022+00:00
[2022-10-13 14:25:42,494] {standard_task_runner.py:52} INFO - Started process 251781 to run task
[2022-10-13 14:25:42,504] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag_bash', 'dbt_docs', 'manual__2022-10-13T21:22:59.806022+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/dbt_bashOperator.py', '--cfg-path', '/tmp/tmp3ukd6_bw', '--error-file', '/tmp/tmpcc88wvru']
[2022-10-13 14:25:42,505] {standard_task_runner.py:80} INFO - Job 94: Subtask dbt_docs
[2022-10-13 14:25:42,592] {task_command.py:370} INFO - Running <TaskInstance: dbt_dag_bash.dbt_docs manual__2022-10-13T21:22:59.806022+00:00 [running]> on host ubuntu
[2022-10-13 14:25:42,662] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt_dag_bash
AIRFLOW_CTX_TASK_ID=dbt_docs
AIRFLOW_CTX_EXECUTION_DATE=2022-10-13T21:22:59.806022+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-13T21:22:59.806022+00:00
[2022-10-13 14:25:42,664] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-13 14:25:42,664] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /home/ubuntu/airflow/dbt_project/ && dbt docs generate']
[2022-10-13 14:25:42,677] {subprocess.py:85} INFO - Output:
[2022-10-13 14:25:47,044] {subprocess.py:92} INFO - 21:25:47  Running with dbt=1.1.0
[2022-10-13 14:25:47,181] {subprocess.py:92} INFO - 21:25:47  Found 6 models, 5 tests, 6 snapshots, 0 analyses, 400 macros, 0 operations, 7 seed files, 2 sources, 0 exposures, 0 metrics
[2022-10-13 14:25:47,185] {subprocess.py:92} INFO - 21:25:47
[2022-10-13 14:25:48,962] {subprocess.py:92} INFO - 21:25:48  Concurrency: 2 threads (target='dev')
[2022-10-13 14:25:48,962] {subprocess.py:92} INFO - 21:25:48
[2022-10-13 14:25:49,392] {subprocess.py:92} INFO - 21:25:49  Done.
[2022-10-13 14:25:49,433] {subprocess.py:92} INFO - 21:25:49  Building catalog
[2022-10-13 14:25:56,928] {subprocess.py:92} INFO - 21:25:56  Catalog written to /home/ubuntu/airflow/dbt_project/target/catalog.json
[2022-10-13 14:25:58,727] {subprocess.py:96} INFO - Command exited with return code 0
[2022-10-13 14:25:58,749] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dbt_dag_bash, task_id=dbt_docs, execution_date=20221013T212259, start_date=20221013T212542, end_date=20221013T212558
[2022-10-13 14:25:58,779] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-13 14:25:58,790] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
