[2022-10-17 10:58:39,155] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_deps scheduled__2022-10-16T00:00:00+00:00 [queued]>
[2022-10-17 10:58:39,160] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt.dbt_deps scheduled__2022-10-16T00:00:00+00:00 [queued]>
[2022-10-17 10:58:39,160] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:58:39,161] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-17 10:58:39,161] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:58:39,172] {taskinstance.py:1377} INFO - Executing <Task(DbtDepsOperator): dbt_deps> on 2022-10-16 00:00:00+00:00
[2022-10-17 10:58:39,175] {standard_task_runner.py:52} INFO - Started process 258368 to run task
[2022-10-17 10:58:39,179] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dbt', 'dbt_deps', 'scheduled__2022-10-16T00:00:00+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/dbt_airflow.py', '--cfg-path', '/tmp/tmppet6qztq', '--error-file', '/tmp/tmpnvxrrmks']
[2022-10-17 10:58:39,180] {standard_task_runner.py:80} INFO - Job 107: Subtask dbt_deps
[2022-10-17 10:58:39,225] {task_command.py:370} INFO - Running <TaskInstance: dbt.dbt_deps scheduled__2022-10-16T00:00:00+00:00 [running]> on host ubuntu
[2022-10-17 10:58:39,270] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt
AIRFLOW_CTX_TASK_ID=dbt_deps
AIRFLOW_CTX_EXECUTION_DATE=2022-10-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-16T00:00:00+00:00
[2022-10-17 10:58:39,271] {dbt_hook.py:117} INFO - dbt deps
[2022-10-17 10:58:39,277] {dbt_hook.py:126} INFO - Output:
[2022-10-17 10:58:41,710] {dbt_hook.py:130} INFO - 17:58:41  Running with dbt=1.1.0
[2022-10-17 10:58:41,721] {dbt_hook.py:130} INFO - 17:58:41  Warning: No packages were found in packages.yml
[2022-10-17 10:58:43,161] {dbt_hook.py:132} INFO - Command exited with return code 0
[2022-10-17 10:58:43,171] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dbt, task_id=dbt_deps, execution_date=20221016T000000, start_date=20221017T175839, end_date=20221017T175843
[2022-10-17 10:58:43,225] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-17 10:58:43,253] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
